338106 modified makefiles and scripts by Matthew

diff --git a/rocrail/package/rocraild b/rocrail/package/rocraild
--- a/rocrail/package/rocraild
+++ b/rocrail/package/rocraild
@@ -12,37 +12,54 @@
 # Description:       Starts the Rocrail Daemon
 ### END INIT INFO
 
-rocraild_BIN=/opt/rocrail/rocrail
-rocraild_PID=/opt/rocrail/rocraild.pid
-rocraild_SH=/opt/rocrail/rocraild.sh
+rocraild_PID=/var/run/rocraild.pid
 
-if [ ! -x $rocraild_BIN ] ; then
+# Look for a rocinit.sh file generated by make install,
+# giving preference to a file in the same directory
+if [ -e "`dirname $0`/rocinit.sh" ] ; then
+	. "`dirname $0`/rocinit.sh"
+elif [ -n "`which rocinit.sh`" ] ; then
+	. rocinit.sh
+else
+	echo "ERROR: rocinit.sh not found"
+	exit 5
+fi
+
+ROCRAIL_LIBEXECCMD=$ROCRAIL_LIBEXECDIR/rocrail
+
+
+if [ ! -x "$ROCRAIL_LIBEXECCMD" ] ; then
 	echo -n "Rocrail not installed ! "
 	exit 5
 fi
 
 case "$1" in
     start)
-	if [ ! -e $rocraild_PID ] ; then
-		echo "Starting Rocrail"
-	else
-		echo "rocraild.pid already exists ! "
-		exit 5
-	fi
- 	su - root -c "$rocraild_SH"
-	;;
+		if [ -e $rocraild_PID ] ; then
+			echo "Rocrail PID file already exists ! "
+			exit 5
+		elif [ -n "`ps a | grep "$ROCRAIL_LIBEXECCMD" | grep -v 'grep'`" ] ; then
+		  echo "Rocrail is already running as a process ! "
+		  exit 5
+		else
+			echo "Starting Rocrail"
+		fi
+		su - root -c "cd $ROCRAIL_HOME && rm -f nohup.out && nohup $ROCRAIL_LIBEXECCMD -l $ROCRAIL_LIBDIR & echo \"\$!\" > $rocraild_PID"
+		if [ -e $rocraild_PID ] ; then
+			echo "Rocrail started with PID `head $rocraild_PID`"
+		fi
+		;;
     stop)
-	if [ -e $rocraild_PID ] ; then
-		echo "Shutting down Rocrail"
-	else
-		echo "Rocrail not running or missing PID File ! "
-		exit 5
-	fi
-	su - root -c "kill `head $rocraild_PID`"
-	su - root -c "rm $rocraild_PID"
-	;;
-*)
-	echo "Usage: $0 {start|stop}"
-	exit 1
-
+		if [ -e $rocraild_PID ] ; then
+			echo "Shutting down Rocrail"
+		else
+			echo "Rocrail PID file not found ! "
+			exit 5
+		fi
+		su - root -c "kill `head $rocraild_PID`"
+		su - root -c "rm -f $rocraild_PID"
+		;;
+	*)
+		echo "Usage: $0 {start|stop}"
+		exit 1
 esac
